// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkgxqffyrfetdwkrcsjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrZ3hxZmZ5cmZldGR3a3Jjc2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MjQzNTIsImV4cCI6MjA1MTIwMDM1Mn0.ahgRnZDjeU8uqEvd2EGsFutg_p3TT_YQu43qBo3wbnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);